title: Training

sections:
  info:
    type: fields
    fields: 
      jeugd:
        type: textarea
        width: 1/2
      mannen:
        type: textarea
        width: 1/2
      vrouwen:
        type: textarea
        width: 1/2
      interesse:
        type: textarea
        width: 1/2
